# -*- coding: utf-8 -*-
"""4-modul SUN'IY

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qcbLC7ZB3ne9x3zLnYJAcbyiKkJX2bE1

# 11-21- guruh talabasi Abdimo'minov Asliddinning
### "SUN'IY INTELLEKT VA NEYRONTO'RLI TEXNOLOGIYALAR" fanidan
# 4-modul
"""

import pandas as pd

dataset=pd.read_excel("uybor.xlsx")
dataset.head(13)

dataset.tail(2) # oxirgi 5 ta qatorni chiqarib beradi

dataset.sample(5)

dataset.info()

dataset.describe()

dataset.sum()

dataset.sum(axis=0)

dataset.mean()

dataset.prod() # ko'paytmani chiqarish

dataset[['price']].idxmin() #Eng kichik elementlar id sini chiqarib beradi

dataset['price'].argmax() # Aholisi eng kichik elementlarni tartib raqamini chiqaradi

dataset.corr()

malumot=dataset
malumot.corrwith(dataset)
